<link href="/news/special/world/11/7_billion/nav/css/nav.css?cachebuster=cb000000001" rel="stylesheet" type="text/css" />
<link href="/news/special/world/11/7_billion/nav/css/nav_624.css?cachebuster=cb000000001" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/news/special/world/11/7_billion/nav/js/tracking.js"></script>

<div id="nav_7_billion">
	<h3><!--#include virtual="/news/special/world/11/7_billion/nav/j_inc/title.inc" --></h3>
	<ul id="nav_content">
		<li>
			<a id="item1" class="item1" href='/news/world-15391515'>
				<div class="nav_caption"><!--#include virtual="/news/special/world/11/7_billion/nav/j_inc/caption1.inc" --></div>
				<img src="/news/special/world/11/7_billion/nav/img/whats_your_number.jpg"/>
			</a>
		</li>
		<li>
			<a id="item2" class="item2" href='/news/world-15368276'>
				<div class="nav_caption"><!--#include virtual="/news/special/world/11/7_billion/nav/j_inc/caption2.inc" --></div>
				<img src="/news/special/world/11/7_billion/nav/img/zambia_144.gif"/>
			</a>
		</li>
		<li>
			<a id="item3" class="item3" href='/news/world-15445092'>
				<div class="nav_caption"><!--#include virtual="/news/special/world/11/7_billion/nav/j_inc/caption3.inc" --></div>
				<img src="/news/special/world/11/7_billion/nav/img/fergus_144.gif"/>
			</a>
		</li>
		<li>
			<a id="item4" class="item4" href='/news/magazine-15449959'>
				<div class="nav_caption"><!--#include virtual="/news/special/world/11/7_billion/nav/j_inc/caption4.inc" --></div>
				<img src="/news/special/world/11/7_billion/nav/img/pop_144x81.jpg"/>
			</a>
		</li>
		<li>
			<a id="item5" class="item5" href='/news/magazine-15494349'>
				<div class="nav_caption"><!--#include virtual="/news/special/world/11/7_billion/nav/j_inc/caption5.inc" --></div>
				<img src="http://news.bbcimg.co.uk/media/images/56352000/jpg/_56352624_pop_graphic_144_2.jpg"/>
			</a>
		</li>
	</ul>
</div>